# NumPy
NumPy is a Python package. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

# What is NumPy?
It is a library consisting of multidimensional array objects and a collection of routines for processing those arrays.

NumPy has put python lists out of the job as NumPy arrays are more efficient, convenient and makes it faster to read or write an item.

In [25]:
import numpy as np

age = np.random.randint(15,45,size=100)

print("Age grp center is : " , np.mean(age))

Age grp center is :  29.52


# Python Lists vs NumPy Arrays – What’s the Difference?
1.Python lists act as an array that can store elements of various types.A list is the Python equivalent of an array,but is resizeable and can contain elements of different types.

2.NumPy arrays that contain only homogeneous elements, i.e. elements having the same data type.

3.With NumPy arrays, you can perform element-wise operations, something which is not possible using Python lists!

4.This is the reason why NumPy arrays are preferred over Python lists when performing mathematical operations on a large amount of data.

# Why use NumPy?
Using NumPy, mathematical and logical operations on arrays can be performed. NumPy also provides high performance.Some of the key features that contribute in the popularity of NumPyare:

1.It is a powerful N-dimensional array object

2.It is a sophisticated broadcasting functions

3.It is a tool for integrating C/C++ and Fortran code

4.It is useful linear algebra, Fourier transform, and random number capabilities

# Import Convention
Since NumPy is a Python Library, it has to be imported first before you start using NumPy. To import NumPy, type in the following command:

In [35]:
import numpy as np

# Creating Numpy Arrays

1.np.array() 1D/2D

2.np.zeros/ones/identity()

3.np.arange()

4.np.linspace()

5.np.copy()

6.np.random() :--. rand/randint

7.np.full()

In [26]:
#1.np.array() 1D/2D

L1 = [1,2,3,4]

A1 = np.array([1,2,3,4,])

print("Data Type of L1 : " , type(L1))
print("Data Type of A1 : " , type(A1))

Data Type of L1 :  <class 'list'>
Data Type of A1 :  <class 'numpy.ndarray'>


In [27]:
A2 = np.array([[1,2,3],[4,5,6]])

print("2D Array \n" , A2)

2D Array 
 [[1 2 3]
 [4 5 6]]


In [32]:
#2.np.zeros/ones/identity()

A3 =  np.zeros((3,3))#Row,col

print("Zeros: \n" , A3)

A4 =  np.ones((3,3))#Row,col

print("Ones: \n" , A4)

A5 =  np.identity(5)

print("identity: \n" , A5)

Zeros: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
identity: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [35]:
L3 = list(range(1,11))

print("Using Python Range Function : " , L3)

A6 = np.arange(1,11)

print("Using Numpy Range Function  : " ,A6)

Using Python Range Function :  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Using Numpy Range Function  :  [ 1  2  3  4  5  6  7  8  9 10]


In [36]:
A7 = np.arange(1,21,2)

A7

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [39]:
#4.np.linspace()
A8 = np.linspace(10,50,5)

A8

array([10., 20., 30., 40., 50.])

In [40]:
#5.np.copy()

A9 = np.copy(A8)

A9

array([10., 20., 30., 40., 50.])

In [54]:
#6.np.random() :--. rand/randint

A10 = np.random.rand(2,3) #rand :--> 0 to 1

A11 = np.round(np.random.rand(2,3), decimals = 2 )

A11

A12 = np.random.randint(10,50,6)#Starting,Ending,Size

A12

array([24, 31, 43, 35, 47, 46])

In [56]:
#7.np.full()

A13 = np.full((3,5),5.5)

A13

array([[5.5, 5.5, 5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5, 5.5]])