In [3]:
import numpy as np


In [2]:
L1 = [10,15,16]
L2 = [11,18,17]

print(L1+L2)

[10, 15, 16, 11, 18, 17]


In [4]:
a1 = np.array([10,15,16])
a2 = np.array([11,18,17])

print(a1+a2)

[21 33 33]



# Broadcasting in NumPy arrays


Broadcasting essentially stretches the smaller ndarray so that it matches the shape of the larger ndarray

In [12]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print('Shape a1 : ' , np.shape(a1) )
print("Dim of a1 : " , np.ndim(a1))

a2 = np.array([[3],[2],[1]])

print('Shape a2 : ' , np.shape(a2) )
print("Dim of a2 : " , np.ndim(a2))


Shape a1 :  (3, 3)
Dim of a1 :  2
Shape a2 :  (3, 1)
Dim of a2 :  2


In [13]:
print(a1)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3]
 [2]
 [1]]


In [14]:
print(a1+a2)

[[ 4  5  6]
 [ 6  7  8]
 [ 8  9 10]]


# Maths with NumPy arrays

In [28]:
a3 = np.random.randint(10,50,size=5)

print("A3 : " ,a3)

print("A3 + 4 : " , a3+4)
print("A3 - 7 : " , a3-7)
print("A3 / 2 : " , a3/2)
print("A3 * 3 : " , a3*3)

A3 :  [17 49 34 36 24]
A3 + 4 :  [21 53 38 40 28]
A3 - 7 :  [10 42 27 29 17]
A3 / 2 :  [ 8.5 24.5 17.  18.  12. ]
A3 * 3 :  [ 51 147 102 108  72]


In [29]:
print(a3**3)
print(28 in a3)
print(21>a3)

[  4913 117649  39304  46656  13824]
False
[ True False False False False]


# Mean, Median and Standard deviation

In [34]:
age = [10,18,17,16,24,17,18,16]

print("Mean : " , np.mean(age))

age = [10,18,17,16,24,17,180,16]
print("Mean : " , np.median(age))

Mean :  17.0
Mean :  17.0


In [35]:
age1 = [21,25]
age2 = [22,24]

print("Age1 Mean : " , np.mean(age1) ,"Age2  Mean : ", np.mean(age2))

Age1 Mean :  23.0 Age2  Mean :  23.0


In [36]:
print("STD of Age 1 : " , np.std(age1) ,"STD pf Age2 :" ,np.std(age2))

STD of Age 1 :  2.0 STD pf Age2 : 1.0


# Append

In [45]:
a4 = np.array([[1,2,3],[4,5,6]])

print("Before append : \n" , a4)

a5 = np.append(a4,[[7,8,9]],axis=0)

print("After append : \n" , a5)

Before append : 
 [[1 2 3]
 [4 5 6]]
After append : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


# Max,Min,sqrt,log10

In [47]:
a7 = np.random.randint(10,66,size=8)

a7

print("MAX : " , np.max(a7))
print("MIN : " , np.min(a7))
print("SQRT : " , np.sqrt(a7))
print("log10 : " , np.log10(a7))

MAX :  58
MIN :  10
SQRT :  [6.164414   7.61577311 4.47213595 6.244998   5.19615242 5.47722558
 3.16227766 4.79583152]
log10 :  [1.5797836  1.76342799 1.30103    1.59106461 1.43136376 1.47712125
 1.         1.36172784]



# Sort

In [49]:
a8 = np.array([11,17,5,13,12,8,1,3])

print(np.sort(a8)[::-1])

[17 13 12 11  8  5  3  1]
