# Transpose of Numpy Array :- np.transpose()



In [6]:
import numpy as np

a1 = np.array([[1,2,3],[4,5,6]])

print("Dim of a1 : " , np.ndim(a1))
print("Shape of a1 : " , np.shape(a1))
print("A1 \n" , a1)
print()

b1 = a1.transpose()

print("Dim of b1 : " , np.ndim(b1))
print("Shape of b1 : " , np.shape(b1))
print("B1 \n" , b1)

Dim of a1 :  2
Shape of a1 :  (2, 3)
A1 
 [[1 2 3]
 [4 5 6]]

Dim of b1 :  2
Shape of b1 :  (3, 2)
B1 
 [[1 4]
 [2 5]
 [3 6]]


# Squeezing a Numpy Array :- np.squeeze()



In [9]:
a2 = np.array([[[1,2,3],[4,5,6]]])

print("Shape of a2 : " , np.shape(a2))
print("Dim of a2 : " , np.ndim(a2))
print("A2 \n" , a2)

b2 = a2.squeeze()

print("Shape of b2 : " , np.shape(b2))
print("Dim of b2 : " , np.ndim(b2))
print("B2 \n" , b2)

Shape of a2 :  (1, 2, 3)
Dim of a2 :  3
A2 
 [[[1 2 3]
  [4 5 6]]]
Shape of b2 :  (2, 3)
Dim of b2 :  2
B2 
 [[1 2 3]
 [4 5 6]]


In [11]:
a3 = np.array([[1,2,3],[4,5,6]])

print("Shape of a3 : " , np.shape(a3))
print("Dim of a3 : " , np.ndim(a3))
print("A3 \n" , a3)
print()

b3 = a3.squeeze()#Note that Squeeze function can be use on 3 & above Dim
print(b3)

Shape of a3 :  (2, 3)
Dim of a3 :  2
A3 
 [[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]


# Flip :-np.flip() method to reverse values in Numpy Array

In [15]:
a4 = np.array([[1,2,3],[4,5,6]])

print("A4 \n", a4)
print()
#Axis : Zero axis ---> Row | One axis ---> column

b4 = np.flip(a4,axis=0)
print("B4 in Row \n", b4)
print()

b5 = np.flip(a4,axis=1)
print("B5 in Column \n", b5)

A4 
 [[1 2 3]
 [4 5 6]]

B4 in Row 
 [[4 5 6]
 [1 2 3]]

B5 in Column 
 [[3 2 1]
 [6 5 4]]


# Indexing & Slicing of Numpy Array

[start : end : step-size]

In [17]:
a5 = np.array([10,20,30,40,50,60,70,80,90,100])
#              0  1  2  3  4  5  6   7  8  9
print("Using Postive indexing : " , a5[4])
print("Using Negative indexing : " , a5[-3])

Using Postive indexing :  50
Using Negative indexing :  80


In [20]:
print(a5[2:7:2])
print(a5[:8])#10-80
print(a5[2::3])#30,60,90 / 

[30 50 70]
[10 20 30 40 50 60 70 80]
[30 60 90]


In [22]:
a6 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a6)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
print(a6[1,1])
print(a6[2,2])
print(a6[1,0])

5
9
4


In [30]:
print(a6[0:1,1:])
print(a6[1:,1:])

[[2 3]]
[[5 6]
 [8 9]]


In [33]:
print(a6[0:2,0:2])

[[1 2]
 [4 5]]
