# Numpy Array Dimension / shape / size

In [1]:
import numpy as np

In [7]:
a1 = np.array([[1,2,3],[4,5,6]])

print("Array a1: \n",a1)
print()

print("Dim of Array a1 : " , np.ndim(a1))
print()

print("Shape of Array a1 : " , np.shape(a1))#(row,col)
print()


print("Number Values in Array a1 : " , np.size(a1))


Array a1: 
 [[1 2 3]
 [4 5 6]]

Dim of Array a1 :  2

Shape of Array a1 :  (2, 3)

Number Values in Array a1 :  6


In [8]:
a2 = np.array([1,2,3,4,5,6])

print("Array a2: \n",a2)
print()

print("Dim of Array a2 : " , np.ndim(a2))
print()

print("Shape of Array a2 : " , np.shape(a2))#(row,col)
print()


print("Number Values in Array a2 : " , np.size(a2))


Array a2: 
 [1 2 3 4 5 6]

Dim of Array a2 :  1

Shape of Array a2 :  (6,)

Number Values in Array a2 :  6


# Reshaping of Numpy Array

In [17]:
a3 = np.array([1,2,3,4,5,6])

print("Shape of Array a3 : \n" , np.shape(a3))
print(a3)

a4 = a3.reshape(3,2)

print("Shape of Array a4 : \n" , np.shape(a4))
print(a4)

Shape of Array a3 : 
 (6,)
[1 2 3 4 5 6]
Shape of Array a4 : 
 (3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [21]:
a5 = np.arange(1,13)

print(a5)

print(a5.reshape(3,4))
print(a5.reshape(6,2))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


# flatten & ravel

In [25]:
a6 = np.array([[1,2,3],[4,5,6]])

print("Before Flatten : \n" ,a6)

a7 = a6.flatten()

print("After Flatten : \n" ,a7)

Before Flatten : 
 [[1 2 3]
 [4 5 6]]
After Flatten : 
 [1 2 3 4 5 6]


In [28]:
a8 = np.array([[1,2,3],[4,5,6]])

print("Before ravel : \n",a8)

a9 =  a8.ravel()

print("After ravel : \n" ,a9)

Before ravel : 
 [[1 2 3]
 [4 5 6]]
After ravel : 
 [1 2 3 4 5 6]


In [33]:
#flatten :--> shallow copy

a6 = np.array([[1,2,3],[4,5,6]])

print("Before Flatten : \n" ,a6)




a7 = a6.flatten()

a7[0] = 10
print("After Flatten : \n" ,a7)
print("After Flatten : \n" ,a6)

Before Flatten : 
 [[1 2 3]
 [4 5 6]]
After Flatten : 
 [10  2  3  4  5  6]
After Flatten : 
 [[1 2 3]
 [4 5 6]]


In [32]:
#ravel :--> deep copy

a8 = np.array([[1,2,3],[4,5,6]])

print("Before ravel : \n",a8)

a9 =  a8.ravel()
a9[0] = 10

print("After ravel : \n" ,a9)

print("After ravel : \n",a8)

Before ravel : 
 [[1 2 3]
 [4 5 6]]
After ravel : 
 [10  2  3  4  5  6]
After ravel : 
 [[10  2  3]
 [ 4  5  6]]


In [40]:
a10 = np.arange(1,37)

a10.reshape(12,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36]])

In [44]:
a11 = np.array([1,2,3,4,5,6,6,7,8])

print(np.ndim(a11))

1
